### ISSUE TITLE
It does work but the image logger only send there roblox cookie :< fix it

### ISSUE THREAD

**Issue by billionee** [Rdmo1/Rdmo1-Multi-Tool#4]
this person managed to hack my discord account and promoted this tool to scam more people, and got people to download free nitro with my account to my trusted friends, i havent even installed this program and malwarebytes shows no viruses but he still gets in so don’t install

**Comment by Avarjj** [comment]
@Rdmo1 add me or u some one create me image logger my disscord psx#7832

i open programme but its says launching and it closes :(

**Comment by logicguy1** [comment]
He can't code so don't expect anything

**Comment by billionee** [comment]
bro changed the title
